### ISSUE TITLE
Support for longer private keys

### ISSUE THREAD

**Issue by andreagdipaolo** [sdr-enthusiasts/docker-radarvirtuel#45]
Radarvirtuel gave me a private key and its first part is 7 characters long.
The container doesn't accept it because it accepts only 4 to 6 characters.
I believe that the check should be edited, because some airports could have more than 99 feeders.
Thanks!

**Comment by kx1t** [comment]
Thanks for bringing this up.  I’ve updated the code to accept any station ID of 4 characters or more. Once the container is rebuilt I’ll close the issue.

**Comment by kx1t** [comment]
Ok, the container has been rebuilt. Could you pull the container and try it if works, and if it doesn’t, please reopen the issue? Thanks again!
